name: sanity_check

defaults:
  - data: TinyImageNet
  - impl: default
  - server: honest-but-curious
  - user: multiuser_aggregate
  - _self_
model: linear

user:
  provide_labels: True

# Server and user:
num_queries: 1
