defaults:
  - _default_optimization_attack
  - _self_
type: invertinggradients

objective:
  type: proj-euclidean
  scale: 0.0001 # need to have a much smaller scale like 0.0001 for euclidean objectives

init: patterned-4

restarts:
  num_trials: 5
  scoring: "cosine-similarity"

optim:
  optimizer: adam
  signed: "soft"
  step_size: 0.1
  boxed: True
  max_iterations: 2500
  step_size_decay: linear
  warmup: 50

  callback: 100 # Print objective value every callback many iterations

regularization:
  total_variation:
    scale: 0
    inner_exp: 2
    outer_exp: 0.5
    double_opponents: False
  features:
    scale: 0
  deep_inversion:
    scale: 0
impl:
  dtype: double
  mixed_precision: False
